name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload static website to Apache server
    runs-on: ubuntu-latest
    environment: PRODUCTION   # <<--- IMPORTANTE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy static files using rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./                         # Archivos del repo
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}   # Llave PRIVADA (sin .pub)
          remote_path: /var/www/indeco/          # La ruta en tu VPS
          remote_port: 22